### ISSUE TITLE
Angular remote in React as host in latest version 18

### ISSUE THREAD

**Issue by nmanthena18** [joemoceri/module-federation-angular-react-vue-hosts-remotes#1]
Do we have any working repo with compatability with latest version like React as host angular as remote.

**Comment by joemoceri** [comment]
Right now it works on React 17, I would try upgrading to 18 and seeing if it still works, if not I'd check the differences between the versions. If it doesn't work, you can find the difference and apply a patch on 18 to get it working. 

The upgrade guide lays out a few of the migrations necessary, but you might not have any issues if you upgrade and apply those migrations
https://react.dev/blog/2022/03/08/react-18-upgrade-guide

It would be nice to have different versions of each framework interacting with each other. Right now it's React 17, Angular 13.2, and Vue 3, and they all use webpack as the build system. I think the goal would be to know which versions of Angular, React and Vue are compatible with each other, find the differences between the ones that aren't, and write patches for each case, but I would try upgrading and seeing if it works first.

**Comment by nmanthena18** [comment]
I did some patch work it’s working good, can you suggest on the route part, it’s better to maintain in the host or its good to maintain in the remote?

**Comment by joemoceri** [comment]
Both for sure. Like if I had a host application with pages specific to itself, you would have routes there, and any remote application that's then loaded would have it's own set of routes relative to where it's being loaded from the host. There's no examples in this project but I found this project for react which uses react router to do that which can be applied to the hosts and remotes here. https://github.com/nebarf/module-federation-react-router-dom

**Comment by nmanthena18** [comment]
I really thankful to you
